version: 1
disable_existing_loggers: false
formatters:
  default:
    format: "%(asctime)s [%(levelname)-8s]: %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
loggers:
  examples_gdrive:
    level: DEBUG
    handlers:
      - console
    propagate: false
root:
  level: INFO
  handlers:
    - console
